### ISSUE TITLE
The newest docker image is broken?

### ISSUE THREAD

**Issue by peilin-ice** [synthego-open/ice#22]
Hi there,

we've been using synthego/ice:latest for over 10 months.  It's been working well till last week when we did a docker pull and got a new image.  All the runs failed with the same python error, and I can reproduce it running test_analysis.py:

E           TypeError: ord() expected string of length 1, but int found

ice/classes/sanger_object.py:112: TypeError

The test env is 
platform darwin -- Python 3.6.4, pytest-3.4.2, py-1.8.0, pluggy-0.6.0

Now we rolled back to an old image we saved before.  But would like to report this bug in case it was overlooked.

Thanks,

Pei

**Comment by graeberlab** [comment]
Have you found a solution to this. I also am having the same trouble.

**Comment by peilin-ice** [comment]
@graeberlab gtk you have the same problem.  We rolled back to a previous working docker image.

**Comment by graeberlab** [comment]
Do you by chance remember which TAG because I tried the vanilla_ICE  tag and had the same problem.

https://hub.docker.com/r/synthego/ice/tags

**Comment by andrewcchang** [comment]
The problem came from latest Biopython (v1.74) which now converts strings to bytes-object. When ICE parse ab1 files, it does not know how to handle that object.  We will update the code soon.  In the meantime, if you want to run python version of ICE, you can downgrade Biopython to v1.72.

**Comment by peilin-ice** [comment]
@graeberlab I don't have the tag, we pulled as latest several months ago.  But the image id is be9de562f6cc

**Comment by peilin-ice** [comment]
@andrewcchang Thanks for the update!

**Comment by andrewcchang** [comment]
Glad it helped! Please let us know if you run into any other problem.
