### ISSUE TITLE
docker permission error

### ISSUE THREAD

**Issue by yinshiyi** [synthego-open/ice#28]
docker pull synthego/ice

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Thanks

**Comment by peilin-ice** [comment]
This sounds like an error in your local environment.

**Comment by yinshiyi** [comment]
you are right, i fixed it now, thanks

**Comment by yinshiyi** [comment]
I have fixed it now thanks
